Repository microapidev/comment-microapi, pull requests merged in 2020-06, with the labels that each got.

#98 write tests for downvote and upvote of comments (#75)
  __test__/api/comment-vote.test.js
Labels: test

#101 feat: add new schema and models
  models/admins.js
  models/applications.js
  models/organizations.js
Labels: enhancement

#99 feat: update swagger docs inline with endpoints
  docs/comments.yaml
  docs/swagger.yaml
  utils/swaggerSpec.js
Labels: enhancement

#103 test: fix function call error
  __test__/api/comment-get.test.js
  __test__/api/comment-post.test.js
  __test__/api/index.test.js
  __test__/helpers/conditionalTests.js
Labels: bug

#135 Create LICENSE
  LICENSE
Labels: documentation

#136 Update readme
  README.md
  models/README.md
  utils/README.md
Labels: documentation

#138 Update commentId in ReplySchema to required field
  models/replies.js
Labels: enhancement

#139 [TEST]: `PATCH /comments/:commentId` Fixes Issue #129
  __test__/api/comment-patch.test.js
  __test__/helpers/conditionalTests.js
Labels: test

#115 Create Controller method to delete a Comment
  controller/commentsController.js
  routes/comments.js
Labels: enhancement

#130 Feat: user can reply to a comment
  controller/repliesController.js
  routes/replies.js
Labels: enhancement

#133 Feat/get reply
  controller/repliesController.js
  routes/replies.js
Labels: enhancement

#107 Feat: flag off comment replies
  controller/repliesController.js
  routes/replies.js
Labels: enhancement

#104 [FEATURE REQUEST] Create controller method to upvote a comment #148
  controller/commentsController.js
  routes/comments.js
Labels: enhancement

#160 Get reply votes
  controller/repliesController.js
  routes/replies.js
Labels: enhancement

#172 [Feature Request] downvote comment endpoint
  controller/commentsController.js
  routes/comments.js
Labels: enhancement

#171 CommentsController - POST /comments: Create controller method to create a comment
  __test__/api/comment-post.test.js
  controller/commentsController.js
  routes/comments.js
Labels: enhancement

#168 CommentsEndpointTests - PATCH /comments/{commentId}/votes/*: Refactor comment upvote and downvote test suite to match new spec
  __test__/api/comment-vote.test.js
Labels: test
